-- Coarse routes over a generated stream graph. World.path validates each loaded leg.
local Route={}
---@class ShinyStreamRouteResult
---@field status 'ok'|'unreachable'|'unloaded'|'budget_exhausted'
---@field visited integer
---@field points ScNavigationPoint[] World-pixel start, paired portals, and goal on success.
---@field revision integer Connectivity snapshot revision; changes after a successful refresh.
local function integer(value,low,high,name)
    assert(type(value)=="number" and value%1==0 and value>=low and value<=high,"invalid "..name)
    return math.tointeger(value)
end
local function coordinate(value,name)
    assert(type(value)=="number" and value==value and math.abs(value)<=1e6,"invalid "..name)
    return value
end
local function key(x,y) return x..":"..y end
local function empty(status,revision) return {status=status,visited=0,points={},revision=revision} end
local function node_at(chunk,column,row)
    if not chunk then return 0 end
    if chunk.labels then return chunk.labels[row][column] or 0 end
    if chunk.full then return chunk.component end
    if chunk.rows and chunk.rows[row]:sub(column,column)=="." then return chunk.component end
    return 0
end
local function adjacency(edges)
    local result={}
    for _,edge in ipairs(edges) do
        local a,b=edge.a,edge.b
        result[a]=result[a] or {}; result[b]=result[b] or {}
        result[a][#result[a]+1]={to=b,edge=edge}
        result[b][#result[b]+1]={to=a,edge=edge}
    end
    return result
end

---@param data table Generated by tools/nav_graph.py.
---@return table
function Route.new(data)
    assert(type(data)=="table" and getmetatable(data)==nil and data.format==1,
        "stream route requires generated format 1 data")
    local cell=integer(data.cell_size,1,256,"route cell size")
    local width=integer(data.chunk_width,1,8192,"route chunk width")
    local height=integer(data.chunk_height,1,8192,"route chunk height")
    assert(width%cell==0 and height%cell==0 and 9*(width//cell)*(height//cell)<=16384 and
        integer(data.cells_x,1,8192,"route columns")==width//cell and
        integer(data.cells_y,1,8192,"route rows")==height//cell,"route cell dimensions disagree")
    local count=integer(data.node_count,0,1048576,"route component count")
    assert(type(data.bounds)=="table" and #data.bounds==4 and type(data.chunks)=="table" and
        type(data.edges)=="table" and #data.edges<=2097152,"invalid route directory")
    local bounds={}
    for i=1,4 do bounds[i]=integer(data.bounds[i],-31250,31250,"route bound") end
    assert(bounds[1]<=bounds[3] and bounds[2]<=bounds[4],"invalid route bounds")
    for i,edge in ipairs(data.edges) do
        assert(type(edge)=="table" and getmetatable(edge)==nil,"invalid route portal")
        local a=integer(edge.a,1,count,"portal source")
        local b=integer(edge.b,1,count,"portal target")
        local ax=integer(edge.ax,-1000000,1000000,"portal x")
        local ay=integer(edge.ay,-1000000,1000000,"portal y")
        local bx=integer(edge.bx,-1000000,1000000,"portal x")
        local by=integer(edge.by,-1000000,1000000,"portal y")
        assert(a~=b and math.abs(ax-bx)+math.abs(ay-by)==1,"route portal must join adjacent components")
    end
    return {data=data,adjacent=adjacency(data.edges),bounds=bounds,overrides={},revision=0,
        refresh=Route.refresh}
end

local function locate(route,x,y)
    local data=route.data
    local cx,cy=math.floor(x/data.chunk_width),math.floor(y/data.chunk_height)
    local bounds=route.bounds
    if cx<bounds[1] or cy<bounds[2] or cx>bounds[3] or cy>bounds[4] then return nil,"unloaded" end
    local name=key(cx,cy)
    local chunk=route.overrides[name] or data.chunks[name]
    if not chunk then return nil,"unloaded" end
    local column=math.floor((x-cx*data.chunk_width)/data.cell_size)+1
    local row=math.floor((y-cy*data.chunk_height)/data.cell_size)+1
    local node=node_at(chunk,column,row)
    if node>0 then return node end
    return nil,"unreachable"
end

local function same_rows(chunk,rows,width,height)
    if chunk.full then
        local open=string.rep(".",width)
        for y=1,height do if rows[y]~=open then return false end end
    elseif chunk.rows then
        for y=1,height do if rows[y]~=chunk.rows[y] then return false end end
    elseif chunk.labels then
        for y=1,height do for x=1,width do
            if (rows[y]:sub(x,x)==".")~=(chunk.labels[y][x]>0) then return false end
        end end
    else
        local blocked=string.rep("#",width)
        for y=1,height do if rows[y]~=blocked then return false end end
    end
    return true
end

local function component_chunk(route,x,y,rows)
    local data=route.data
    local width,height=data.cells_x,data.cells_y
    local ordinal=(y-route.bounds[2])*(route.bounds[3]-route.bounds[1]+1)+x-route.bounds[1]
    local labels,queue={},{}
    local count=0
    for row=0,height-1 do for column=0,width-1 do
        local start=row*width+column+1
        if rows[row+1]:sub(column+1,column+1)=="." and not labels[start] then
            count=count+1; assert(count<=1024,"route chunk exceeds component capacity")
            local id=data.node_count+ordinal*1024+count
            labels[start]=id; queue[1]=start
            local head,tail=1,1
            while head<=tail do
                local cell=queue[head]; head=head+1
                local px,py=(cell-1)%width,(cell-1)//width
                local function visit(nx,ny)
                    if nx>=0 and ny>=0 and nx<width and ny<height and
                        rows[ny+1]:sub(nx+1,nx+1)=="." then
                        local neighbor=ny*width+nx+1
                        if not labels[neighbor] then
                            labels[neighbor]=id; tail=tail+1; queue[tail]=neighbor
                        end
                    end
                end
                visit(px,py-1); visit(px-1,py); visit(px+1,py); visit(px,py+1)
            end
        end
    end end
    local grid={}
    for row=1,height do
        local line={}
        for column=1,width do line[column]=labels[(row-1)*width+column] or 0 end
        grid[row]=line
    end
    return {x=x,y=y,rows=rows,labels=grid}
end

local function rebuild(route,overrides)
    local data=route.data
    local width,height=data.cells_x,data.cells_y
    local edges={}
    local function changed_at(x,y) return overrides[key(x,y)]~=nil end
    for _,edge in ipairs(data.edges) do
        if not changed_at(edge.ax//width,edge.ay//height) and
            not changed_at(edge.bx//width,edge.by//height) then edges[#edges+1]=edge end
    end
    local active={}
    for _,chunk in pairs(overrides) do active[#active+1]=chunk end
    table.sort(active,function(a,b) return a.x==b.x and a.y<b.y or a.x<b.x end)
    local seen_boundaries={}
    for _,chunk in ipairs(active) do
        local x,y=chunk.x,chunk.y
        for _,neighbor in ipairs({{x+1,y},{x,y+1},{x-1,y},{x,y-1}}) do
            local nx,ny=neighbor[1],neighbor[2]
            if nx>=route.bounds[1] and ny>=route.bounds[2] and
                nx<=route.bounds[3] and ny<=route.bounds[4] then
                local ax,ay,bx,by=x,y,nx,ny
                if bx<ax or by<ay then ax,ay,bx,by=bx,by,ax,ay end
                local boundary=key(ax,ay).."|"..key(bx,by)
                if not seen_boundaries[boundary] then
                    seen_boundaries[boundary]=true
                    local left=overrides[key(ax,ay)] or data.chunks[key(ax,ay)]
                    local right=overrides[key(bx,by)] or data.chunks[key(bx,by)]
                    local seen_nodes={}
                    local horizontal=bx>ax
                    local length=horizontal and height or width
                    for cell=1,length do
                        local a,b
                        local portal
                        if horizontal then
                            a=node_at(left,width,cell); b=node_at(right,1,cell)
                            portal={ax=ax*width+width-1,ay=ay*height+cell-1,
                                bx=bx*width,by=by*height+cell-1}
                        else
                            a=node_at(left,cell,height); b=node_at(right,cell,1)
                            portal={ax=ax*width+cell-1,ay=ay*height+height-1,
                                bx=bx*width+cell-1,by=by*height}
                        end
                        local pair=a..":"..b
                        if a>0 and b>0 and not seen_nodes[pair] then
                            seen_nodes[pair]=true
                            portal.a,portal.b=a,b
                            edges[#edges+1]=portal
                        end
                    end
                end
            end
        end
    end
    return adjacency(edges)
end

---@param route table Result of Route.new.
---@param mask ScNavigationMask Current native mask for the published region and graph radius.
---@param chunks table[] Dense array of confirmed loaded {x,y} chunk coordinates.
---@return integer changed Number of chunks whose passability changed.
function Route.refresh(route,mask,chunks)
    local data=route.data
    assert(type(mask)=="table" and getmetatable(mask)==nil and type(chunks)=="table" and
        getmetatable(chunks)==nil and #chunks<=16384,"route refresh requires a mask and loaded chunks")
    local cell=data.cell_size
    assert(integer(mask.cell_size,1,256,"mask cell size")==cell and
        coordinate(mask.radius,"mask radius")==data.radius,"route mask scale/radius disagrees with graph")
    local origin_x,origin_y=coordinate(mask.x,"mask x"),coordinate(mask.y,"mask y")
    local mask_width=integer(mask.width,1,16384,"mask width")
    local mask_height=integer(mask.height,1,16384,"mask height")
    local halo=mask.radius>cell/2 and math.ceil(mask.radius/cell) or 0
    assert(mask_width*mask_height<=16384 and type(mask.rows)=="table" and
        #mask.rows==mask_height,"invalid route mask rows")
    for i=1,mask_height do
        local row=mask.rows[i]
        assert(type(row)=="string" and #row==mask_width and not row:find("[^.#]"),"invalid route mask row")
    end
    local overrides={}
    for name,chunk in pairs(route.overrides) do overrides[name]=chunk end
    local count,entries,seen=0,0,{}
    for i,chunk in ipairs(chunks) do
        entries=i
        assert(type(chunk)=="table" and getmetatable(chunk)==nil,"invalid route chunk")
        local x=integer(chunk.x,route.bounds[1],route.bounds[3],"route chunk x")
        local y=integer(chunk.y,route.bounds[2],route.bounds[4],"route chunk y")
        local name=key(x,y)
        assert(not seen[name],"duplicate route chunk"); seen[name]=true
        local column=(x*data.chunk_width-origin_x)/cell
        local row=(y*data.chunk_height-origin_y)/cell
        assert(column%1==0 and row%1==0 and column>=halo and row>=halo and
            column+data.cells_x+halo<=mask_width and row+data.cells_y+halo<=mask_height,
            "route mask does not cover the chunk and required clearance halo")
        local rows={}
        for j=1,data.cells_y do rows[j]=mask.rows[row+j]:sub(column+1,column+data.cells_x) end
        local old=overrides[name] or data.chunks[name]
        if not same_rows(old,rows,data.cells_x,data.cells_y) then
            overrides[name]=not same_rows(data.chunks[name],rows,data.cells_x,data.cells_y)
                and component_chunk(route,x,y,rows) or nil
            count=count+1
        end
    end
    for index in pairs(chunks) do integer(index,1,entries,"route chunk index") end
    if count==0 then return 0 end
    assert(route.revision<4503599627370495,"route revision exhausted")
    local adjacent=rebuild(route,overrides)
    route.overrides,route.adjacent,route.revision=overrides,adjacent,route.revision+1
    return count
end

---@param route table Result of Route.new.
---@param sx number Start world-pixel x.
---@param sy number Start world-pixel y.
---@param gx number Goal world-pixel x.
---@param gy number Goal world-pixel y.
---@param budget? integer Maximum component expansions, default 16384.
---@return ShinyStreamRouteResult
function Route.route(route,sx,sy,gx,gy,budget)
    coordinate(sx,"route start x"); coordinate(sy,"route start y")
    coordinate(gx,"route goal x"); coordinate(gy,"route goal y")
    budget=integer(budget or 16384,1,1048576,"route node budget")
    local start,reason=locate(route,sx,sy)
    if not start then return empty(reason,route.revision) end
    local goal,goal_reason=locate(route,gx,gy)
    if not goal then return empty(goal_reason,route.revision) end
    if start==goal then return {status="ok",visited=0,points={{x=sx,y=sy},{x=gx,y=gy}},revision=route.revision} end
    local queue,previous,through={start},{[start]=0},{}
    local head,visited=1,0
    while head<=#queue and visited<budget do
        local node=queue[head]; head=head+1; visited=visited+1
        for _,step in ipairs(route.adjacent[node] or {}) do
            local other=step.to
            if previous[other]==nil then
                previous[other]=node; through[other]=step.edge
                if other==goal then
                    local legs={}
                    while other~=start do
                        local edge=through[other]
                        local source=previous[other]
                        legs[#legs+1]={edge=edge,forward=edge.a==source}
                        other=source
                    end
                    local points={{x=sx,y=sy}}
                    local cell=route.data.cell_size
                    local function point(x,y)
                        points[#points+1]={x=(x+.5)*cell,y=(y+.5)*cell}
                    end
                    for i=#legs,1,-1 do
                        local leg=legs[i]; local edge=leg.edge
                        if leg.forward then point(edge.ax,edge.ay); point(edge.bx,edge.by)
                        else point(edge.bx,edge.by); point(edge.ax,edge.ay) end
                    end
                    points[#points+1]={x=gx,y=gy}
                    return {status="ok",visited=visited,points=points,revision=route.revision}
                end
                queue[#queue+1]=other
            end
        end
    end
    return {status=head<=#queue and "budget_exhausted" or "unreachable",visited=visited,
        points={},revision=route.revision}
end

return Route
