-- Coarse routes over a generated stream graph. World.path validates each loaded leg.
local Route={}
---@class ShinyStreamRouteResult
---@field status 'ok'|'unreachable'|'unloaded'|'budget_exhausted'
---@field visited integer
---@field points ScNavigationPoint[] World-pixel start, paired portals, and goal on success.
local function integer(value,low,high,name)
    assert(type(value)=="number" and value%1==0 and value>=low and value<=high,"invalid "..name)
    return math.tointeger(value)
end
local function coordinate(value,name)
    assert(type(value)=="number" and value==value and math.abs(value)<=1e6,"invalid "..name)
    return value
end
local function key(x,y) return x..":"..y end
local function empty(status) return {status=status,visited=0,points={}} end

---@param data table Generated by tools/nav_graph.py.
---@return table
function Route.new(data)
    assert(type(data)=="table" and getmetatable(data)==nil and data.format==1,
        "stream route requires generated format 1 data")
    local cell=integer(data.cell_size,1,256,"route cell size")
    local width=integer(data.chunk_width,1,8192,"route chunk width")
    local height=integer(data.chunk_height,1,8192,"route chunk height")
    assert(width%cell==0 and height%cell==0 and
        integer(data.cells_x,1,8192,"route columns")==width//cell and
        integer(data.cells_y,1,8192,"route rows")==height//cell,"route cell dimensions disagree")
    local count=integer(data.node_count,0,1048576,"route component count")
    assert(type(data.bounds)=="table" and #data.bounds==4 and type(data.chunks)=="table" and
        type(data.edges)=="table" and #data.edges<=2097152,"invalid route directory")
    local bounds={}
    for i=1,4 do bounds[i]=integer(data.bounds[i],-31250,31250,"route bound") end
    assert(bounds[1]<=bounds[3] and bounds[2]<=bounds[4],"invalid route bounds")
    local adjacent={}
    for i,edge in ipairs(data.edges) do
        assert(type(edge)=="table" and getmetatable(edge)==nil,"invalid route portal")
        local a=integer(edge.a,1,count,"portal source")
        local b=integer(edge.b,1,count,"portal target")
        local ax=integer(edge.ax,-1000000,1000000,"portal x")
        local ay=integer(edge.ay,-1000000,1000000,"portal y")
        local bx=integer(edge.bx,-1000000,1000000,"portal x")
        local by=integer(edge.by,-1000000,1000000,"portal y")
        assert(a~=b and math.abs(ax-bx)+math.abs(ay-by)==1,"route portal must join adjacent components")
        adjacent[a]=adjacent[a] or {}; adjacent[b]=adjacent[b] or {}
        adjacent[a][#adjacent[a]+1]={to=b,edge=edge}
        adjacent[b][#adjacent[b]+1]={to=a,edge=edge}
    end
    return {data=data,adjacent=adjacent,bounds=bounds}
end

local function locate(route,x,y)
    local data=route.data
    local cx,cy=math.floor(x/data.chunk_width),math.floor(y/data.chunk_height)
    local bounds=route.bounds
    if cx<bounds[1] or cy<bounds[2] or cx>bounds[3] or cy>bounds[4] then return nil,"unloaded" end
    local chunk=data.chunks[key(cx,cy)]
    if not chunk then return nil,"unloaded" end
    local column=math.floor((x-cx*data.chunk_width)/data.cell_size)+1
    local row=math.floor((y-cy*data.chunk_height)/data.cell_size)+1
    if chunk.full then return chunk.component end
    if chunk.rows then
        if chunk.rows[row]:sub(column,column)=="." then return chunk.component end
    elseif chunk.labels then
        local node=chunk.labels[row][column]
        if node and node>0 then return node end
    end
    return nil,"unreachable"
end

---@param route table Result of Route.new.
---@param sx number Start world-pixel x.
---@param sy number Start world-pixel y.
---@param gx number Goal world-pixel x.
---@param gy number Goal world-pixel y.
---@param budget? integer Maximum component expansions, default 16384.
---@return ShinyStreamRouteResult
function Route.route(route,sx,sy,gx,gy,budget)
    coordinate(sx,"route start x"); coordinate(sy,"route start y")
    coordinate(gx,"route goal x"); coordinate(gy,"route goal y")
    budget=integer(budget or 16384,1,1048576,"route node budget")
    local start,reason=locate(route,sx,sy)
    if not start then return empty(reason) end
    local goal,goal_reason=locate(route,gx,gy)
    if not goal then return empty(goal_reason) end
    if start==goal then return {status="ok",visited=0,points={{x=sx,y=sy},{x=gx,y=gy}}} end
    local queue,previous,through={start},{[start]=0},{}
    local head,visited=1,0
    while head<=#queue and visited<budget do
        local node=queue[head]; head=head+1; visited=visited+1
        for _,step in ipairs(route.adjacent[node] or {}) do
            local other=step.to
            if previous[other]==nil then
                previous[other]=node; through[other]=step.edge
                if other==goal then
                    local legs={}
                    while other~=start do
                        local edge=through[other]
                        local source=previous[other]
                        legs[#legs+1]={edge=edge,forward=edge.a==source}
                        other=source
                    end
                    local points={{x=sx,y=sy}}
                    local cell=route.data.cell_size
                    local function point(x,y)
                        points[#points+1]={x=(x+.5)*cell,y=(y+.5)*cell}
                    end
                    for i=#legs,1,-1 do
                        local leg=legs[i]; local edge=leg.edge
                        if leg.forward then point(edge.ax,edge.ay); point(edge.bx,edge.by)
                        else point(edge.bx,edge.by); point(edge.ax,edge.ay) end
                    end
                    points[#points+1]={x=gx,y=gy}
                    return {status="ok",visited=visited,points=points}
                end
                queue[#queue+1]=other
            end
        end
    end
    return {status=head<=#queue and "budget_exhausted" or "unreachable",visited=visited,points={}}
end

return Route
