#!/usr/bin/env python3
"""Generate LuaLS field contracts and supplemental declarations from native --api builds."""
import argparse
import json
from pathlib import Path
import re
import subprocess

MARKER = '-- BEGIN GENERATED COMPLETE API'


def literal(value):
    if value is None:
        return 'nil'
    if isinstance(value, float):
        return str(int(value)) if value.is_integer() else format(value, '.15g')
    return json.dumps(value, ensure_ascii=False)


def field_description(field):
    text = field.get('description','')
    if field.get('readonly'):
        text = 'Read-only. '+text
    if 'minimum' in field:
        text += f' Range {literal(field["minimum"])}..{literal(field["maximum"])}.'
    if field.get('exclusive_maximum'):
        text += ' Maximum is exclusive.'
    if 'maximum_bytes' in field:
        text += f' At most {literal(field["maximum_bytes"])} bytes.'
    if 'default' in field:
        text += f' Default {literal(field["default"])}.'
    if 'default_by_resource' in field:
        text += ' Default by resource: '+literal(field['default_by_resource'])+'.'
    return text


def function_annotations(name, entry):
    contract = entry['contract']
    lines = ['---'+entry['description'], '---Phases: '+', '.join(contract['phases'])+'.']
    if 'capacity' in contract:
        lines.append('---Capacity: '+contract['capacity']+'.')
    if mutation:=contract.get('mutation'):
        condition=' is supplied (including nil)' if mutation['when']=='present' else ' is non-nil'
        lines.append('---When '+mutation['parameter']+condition+', phases: '+', '.join(mutation['phases'])+'.')
    for param in contract['parameters']:
        optional = '' if param.get('required', True) else '?'
        detail=field_description(param).strip()
        lines.append(f'---@param {param["name"]}{optional} {param["type"]}'+(' # '+detail if detail else ''))
    for result in contract['returns']:
        lines.append('---@return '+result['type']+(' '+result['name'] if 'name' in result else '')+
                     (' # '+result['description'] if result.get('description') else ''))
    arguments = ', '.join(p['name'] for p in contract['parameters'])
    lines.append(f'function {name}({arguments}) end')
    return lines


def generate(binaries, destination, reference=None, check=False):
    source = destination.read_text(encoding='utf-8').split(MARKER)[0].rstrip()
    declared = set(re.findall(r'function\s+([\w.:]+)\(', source))
    contracts, types = {}, {}
    for binary in binaries:
        metadata = json.loads(subprocess.check_output([str(binary.resolve()), '--api'], encoding='utf-8'))
        if metadata.get('contract_version') != 1:
            raise ValueError(f'{binary}: expected contract_version 1')
        for name, contract in metadata['types'].items():
            if name in types and types[name] != contract:
                raise ValueError(f'{name}: field contracts differ between builds')
            types[name] = contract
        for contract in metadata['functions']:
            contracts[contract['name'].replace('ScNetSession:', 'session:')] = contract
    reference_lines = ['# Native API contracts', '',
                       'Generated by `tools/api_docs.py`; edit the native contract tables.', '',
                       'Registered function contracts are generated from `--api`. Record types listed',
                       'below have structured fields; open dictionaries and resource-specific constraints',
                       'also use the descriptions and [authoring annotations](api.lua).', '']
    for name, contract in sorted(types.items()):
        block = ['---@class '+name, '-- Fields generated from native --api.']
        reference_lines += ['## '+name, '', '| Field | Type | Contract |', '| --- | --- | --- |']
        for field in contract['fields']:
            optional = '' if field['required'] else '?'
            description = field_description(field)
            block.append(f'---@field {field["name"]}{optional} {field["type"]} # {description}')
            field_type = field['type'].replace('|', r'\|')
            reference_lines.append(f'| {field["name"]}{optional} | {field_type} | {description} |')
        reference_lines += ['', *('- '+c for c in contract['constraints']), '']
        # Replace only the class fields, never following namespace/functions/aliases.
        pattern = r'^---@class '+re.escape(name)+r'\b[^\n]*\n(?:(?:---@field[^\n]*|-- Fields generated from native --api\.)\n)*'
        source, count = re.subn(pattern, lambda _: '\n'.join(block)+'\n', source, count=1, flags=re.M)
        if count == 0:
            # New native types join the annotation preamble before the next class.
            position = source.index('---@class ')
            source = source[:position]+'\n'.join(block)+'\n\n'+source[position:]
    reference_lines += ['## Functions', '', '| Function | Parameters | Returns | Phases |', '| --- | --- | --- | --- |']
    for name, entry in sorted(contracts.items()):
        if not entry.get('contract'):
            continue
        contract = entry['contract']
        params = ', '.join(p['name']+('?' if not p.get('required',True) else '')+': '+p['type']+
            (' = '+literal(p['default']) if 'default' in p else '') for p in contract['parameters']).replace('|', r'\|')
        returns = ', '.join((r['name']+': ' if 'name' in r else '')+r['type'] for r in contract['returns']).replace('|', r'\|') or 'none'
        phases=', '.join(contract['phases'])
        if mutation:=contract.get('mutation'):
            condition=' supplied (including nil)' if mutation['when']=='present' else ' non-nil'
            phases+='; '+mutation['parameter']+condition+': '+', '.join(mutation['phases'])
        reference_lines.append(f'| {name} | {params} | {returns} | {phases} |')
        if name in declared:
            # Function prose/annotations may touch a class or alias without a blank line.
            # Preserve type declarations rather than swallowing every preceding --- line.
            annotation = r'(?:[^@\n][^\n]*|@(?:param|return|overload|deprecated|nodiscard|async|generic|vararg)\b[^\n]*)?'
            pattern = r'(?:^---'+annotation+r'\n)*^function '+re.escape(name)+r'\([^\n]*\) end'
            source, count = re.subn(pattern, lambda _: '\n'.join(function_annotations(name, entry)), source, count=1, flags=re.M)
            if count != 1:
                raise ValueError(f'{name}: expected a single annotation declaration')
    reference_lines.append('')
    lines = [source, '', MARKER, '-- Regenerate with tools/api_docs.py using full and lightweight builds.']
    namespaces = sorted({name.rsplit('.', 1)[0] for name in contracts if name.startswith('sc.') and name.count('.') > 1})
    for namespace in namespaces:
        if not re.search(re.escape(namespace)+r'\s*=', source):
            lines.append(namespace+' = {}')
    for name, contract in sorted(contracts.items()):
        if name in declared:
            continue
        if contract.get('contract'):
            lines.extend(function_annotations(name, contract))
            continue
        lines.append('---'+contract.get('description', contract.get('summary', '')))
        lines.append('---'+contract.get('signature', ''))
        # The source signature remains visible even for overloads and rich tables.
        lines.append('function '+name+'(...) end')
    outputs = {destination: '\n'.join(lines)+'\n'}
    if reference:
        outputs[reference] = '\n'.join(reference_lines)
    for path, text in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                raise ValueError(f'{path}: generated contract is out of date')
        else:
            path.write_text(text, encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('binaries', type=Path, nargs='+')
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[1]/'docs/api.lua')
    parser.add_argument('--reference', type=Path, help='write the generated field reference')
    parser.add_argument('--check', action='store_true', help='fail on stale output without writing')
    args = parser.parse_args()
    try:
        generate(args.binaries, args.output, args.reference, args.check)
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        parser.exit(1, f'{error}\n')
